// Auto-generated by scripts/optimize-images.js
export interface GalleryItem {
  id: string;
  title: string;
  category: string;
  description: string;
  thumbnail: string;
  full: string;
}

export const galleryItems: GalleryItem[] = [
  {
    "id": "unnamed (1)",
    "title": "Elegant Arabic Bel Pattern",
    "category": "Arabic Mehndi",
    "description": "Bold outlines and delicate fillings in a flowing diagonal pattern, perfect for bridesmaids.",
    "thumbnail": "/img/optimized/thumbnail-unnamed (1).webp",
    "full": "/img/optimized/full-unnamed (1).webp"
  },
  {
    "id": "unnamed (10)",
    "title": "Glamorous Evening Party Makeup",
    "category": "Makeup",
    "description": "Dramatic smoky eyes paired with a nude lip, perfect for receptions and cocktail parties.",
    "thumbnail": "/img/optimized/thumbnail-unnamed (10).webp",
    "full": "/img/optimized/full-unnamed (10).webp"
  },
  {
    "id": "unnamed (11)",
    "title": "Academy Professional Training Class",
    "category": "Classes",
    "description": "Sangeeta guiding students on cone holding, pressure control, and basic line work.",
    "thumbnail": "/img/optimized/thumbnail-unnamed (11).webp",
    "full": "/img/optimized/full-unnamed (11).webp"
  },
  {
    "id": "unnamed (12)",
    "title": "Dulhan Full Hand Mehndi Detail",
    "category": "Bridal Mehndi",
    "description": "Exquisite detailing up to the elbows, capturing traditional doli and shehnai motifs.",
    "thumbnail": "/img/optimized/thumbnail-unnamed (12).webp",
    "full": "/img/optimized/full-unnamed (12).webp"
  },
  {
    "id": "unnamed (13)",
    "title": "Bold Leafy Arabic Mehndi",
    "category": "Arabic Mehndi",
    "description": "Shaded floral trail featuring bold leafy structures and modern negative spaces.",
    "thumbnail": "/img/optimized/thumbnail-unnamed (13).webp",
    "full": "/img/optimized/full-unnamed (13).webp"
  },
  {
    "id": "unnamed (14)",
    "title": "Contemporary Indo-Arabic Grid",
    "category": "Indo Arabic",
    "description": "Symmetrical checkers mixed with delicate vines, covering both front and back hands.",
    "thumbnail": "/img/optimized/thumbnail-unnamed (14).webp",
    "full": "/img/optimized/full-unnamed (14).webp"
  },
  {
    "id": "unnamed (15)",
    "title": "Groom & Bride Portrait Close-up",
    "category": "Portrait Mehndi",
    "description": "A highly detailed close-up of a portrait mehndi, showcasing Sangeeta’s fine-line artistry.",
    "thumbnail": "/img/optimized/thumbnail-unnamed (15).webp",
    "full": "/img/optimized/full-unnamed (15).webp"
  },
  {
    "id": "unnamed (16)",
    "title": "Traditional Maharashtrian Bridal Makeup",
    "category": "Makeup",
    "description": "Classic Nauvari saree styling with a glowing base, traditional crescent bindi, and heavy gold jewelry makeup.",
    "thumbnail": "/img/optimized/thumbnail-unnamed (16).webp",
    "full": "/img/optimized/full-unnamed (16).webp"
  },
  {
    "id": "unnamed (17)",
    "title": "Advanced Stroke & Shading Practice",
    "category": "Classes",
    "description": "Hands-on practice on acrylic hands, focusing on shading techniques, thick-and-thin lines, and speed.",
    "thumbnail": "/img/optimized/thumbnail-unnamed (17).webp",
    "full": "/img/optimized/full-unnamed (17).webp"
  },
  {
    "id": "unnamed (2)",
    "title": "Modern Indo-Arabic Fusion",
    "category": "Indo Arabic",
    "description": "A blend of traditional Indian structure with bold Arabic negative spaces and geometric symmetry.",
    "thumbnail": "/img/optimized/thumbnail-unnamed (2).webp",
    "full": "/img/optimized/full-unnamed (2).webp"
  },
  {
    "id": "unnamed (3)",
    "title": "Custom Couple Portrait Henna",
    "category": "Portrait Mehndi",
    "description": "Stunning hand-drawn couple portraits depicting wedding rituals, customized for the bride.",
    "thumbnail": "/img/optimized/thumbnail-unnamed (3).webp",
    "full": "/img/optimized/full-unnamed (3).webp"
  },
  {
    "id": "unnamed (4)",
    "title": "Classic Indian Traditional Mehndi",
    "category": "Traditional",
    "description": "Full coverage hand mehndi featuring classic paisley, lotus, and net designs.",
    "thumbnail": "/img/optimized/thumbnail-unnamed (4).webp",
    "full": "/img/optimized/full-unnamed (4).webp"
  },
  {
    "id": "unnamed (5)",
    "title": "Delicate Engagement Design",
    "category": "Engagement",
    "description": "Graceful and light back-hand mehndi, designed to complement the engagement ring.",
    "thumbnail": "/img/optimized/thumbnail-unnamed (5).webp",
    "full": "/img/optimized/full-unnamed (5).webp"
  },
  {
    "id": "unnamed (6)",
    "title": "Festive Karwa Chauth Special",
    "category": "Festival",
    "description": "Traditional motifs representing love and celebration for the festive season.",
    "thumbnail": "/img/optimized/thumbnail-unnamed (6).webp",
    "full": "/img/optimized/full-unnamed (6).webp"
  },
  {
    "id": "unnamed (7)",
    "title": "Cute Minimalist Henna for Kids",
    "category": "Kids",
    "description": "Simple and adorable flowers and butterflies, crafted with organic safe henna for little hands.",
    "thumbnail": "/img/optimized/thumbnail-unnamed (7).webp",
    "full": "/img/optimized/full-unnamed (7).webp"
  },
  {
    "id": "unnamed (8)",
    "title": "Chic Minimalist Mandala",
    "category": "Minimal",
    "description": "A modern, clean circular mandala on the palm with neat finger caps, perfect for minimalist styling.",
    "thumbnail": "/img/optimized/thumbnail-unnamed (8).webp",
    "full": "/img/optimized/full-unnamed (8).webp"
  },
  {
    "id": "unnamed (9)",
    "title": "Radiant Royal Bridal Makeup",
    "category": "Makeup",
    "description": "Flawless glowing base with subtle bronze eyes and rich crimson lips, customized for the big day.",
    "thumbnail": "/img/optimized/thumbnail-unnamed (9).webp",
    "full": "/img/optimized/full-unnamed (9).webp"
  },
  {
    "id": "unnamed",
    "title": "Royal Rajasthani Bridal Henna",
    "category": "Bridal Mehndi",
    "description": "Intricate traditional full-hand bridal mehndi featuring royal court motifs, peacocks, and floral mesh details.",
    "thumbnail": "/img/optimized/thumbnail-unnamed.webp",
    "full": "/img/optimized/full-unnamed.webp"
  }
];
